"use client";
import { Layout } from "@/components/genreral/layout";
import { useParams } from "next/navigation";
export default function TranscriptPage() {
    const { id } = useParams();

    return (
        <Layout>
            <div className="pt-20">
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
                <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet sequi eligendi saepe qui praesentium dolores, a corporis repudiandae natus, nulla minima laboriosam maxime pariatur culpa itaque alias perspiciatis incidunt libero?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Harum provident ab natus ea dolorem pariatur quam vero, sint nobis qui et perferendis optio, voluptatibus accusantium ad, eveniet ex nesciunt deserunt?</h1>
            </div>
        </Layout>
    );
}